apiVersion: v1
kind: Namespace
metadata:
  name: "autopilot-lab"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data
  namespace: autopilot-lab
  labels:
    app: postgres
spec:
  storageClassName: px-csi-db
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: autopilot-lab
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17.5
        ports:
        - containerPort: 5432
        env:
        - name: PGUSER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data
