{
 "title": "Portworx Volume Dashboard Revised",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(px_cluster_cpu_percent,cluster)"
    }
   },
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(px_volume_usage_bytes{cluster=~\"$Cluster\"},exported_namespace)"
    }
   },
   {
    "name": "PVC",
    "label": "PVC Name",
    "query": {
     "query": "label_values(px_volume_usage_bytes{cluster=~\"$Cluster\", exported_namespace=~\"$Namespace\"},pvc)"
    }
   },
   { "name": "ViewMode", "query": "Top K : 1, All Data : 9999" }
  ]
 },
 "panels": [
  { "title": "All Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg Read Latency (1m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(px_volume_read_latency_seconds{cluster=~\"$Cluster\"})",
     "legendFormat": "Avg Read Latency"
    }
   ]
  },
  {
   "title": "Top n Volumes by Capacity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, max((px_volume_usage_bytes{cluster=~\"$Cluster\"} / px_volume_capacity_bytes{cluster=~\"$Cluster\"}) * 100) by (exported_namespace, pvc))",
     "legendFormat": "{{exported_namespace}}/{{pvc}}"
    }
   ]
  },
  {
   "title": "Top n Volumes by IO depth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, max(px_volume_depth_io{cluster=~\"$Cluster\"}) by (exported_namespace, pvc))",
     "legendFormat": "{{exported_namespace}}/{{pvc}}"
    }
   ]
  },
  {
   "title": "Avg Write Latency (1m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(px_volume_write_latency_seconds{cluster=~\"$Cluster\"})",
     "legendFormat": "Avg Write Latency"
    }
   ]
  },
  { "title": "Cluster: [[Cluster]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "Cluster" },
  {
   "title": "Current Replication Level (HA)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($ViewMode, max(px_volume_currhalevel{cluster=~\"$Cluster\", exported_namespace=~\"$Namespace\", pvc=~\"$PVC\"}) by (exported_namespace, pvc))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{exported_namespace}}/{{pvc}}",
     "measurement": "px_volume_halevel",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "I/O Priority",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($ViewMode, max(px_volume_iopriority{cluster=~\"$Cluster\", exported_namespace=~\"$Namespace\", pvc=~\"$PVC\"}) by (exported_namespace, pvc))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{exported_namespace}}/{{pvc}}/{{volumename}}",
     "measurement": "px_volume_halevel",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "px_volume_read_latency_seconds{cluster=~\"$Cluster\", exported_namespace=~\"$Namespace\", pvc=~\"$PVC\"}",
     "legendFormat": "{{exported_namespace}}/{{pvc}}/{{volumename}}"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "px_volume_write_latency_seconds{cluster=~\"$Cluster\", exported_namespace=~\"$Namespace\", pvc=~\"$PVC\"}",
     "legendFormat": "{{exported_namespace}}/{{pvc}}/{{volumename}}"
    }
   ]
  },
  {
   "title": "Volume: Used vs. Total Capacity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Disk Capacity",
     "expr": "px_volume_capacity_bytes{cluster=~\"$Cluster\", exported_namespace=~\"$Namespace\", pvc=~\"$PVC\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Capacity - {{exported_namespace}}/{{pvc}}/{{volumename}}",
     "measurement": "px_volume_capacity_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Disk Usage",
     "expr": "px_volume_usage_bytes{cluster=~\"$Cluster\", exported_namespace=~\"$Namespace\", pvc=~\"$PVC\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Usage - {{exported_namespace}}/{{pvc}}/{{volumename}}",
     "measurement": "px_volume_usage_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Configured Replication Level (HA)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($ViewMode, max(px_volume_halevel{cluster=~\"$Cluster\", exported_namespace=~\"$Namespace\", pvc=~\"$PVC\"}) by (exported_namespace, pvc))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{exported_namespace}}/{{pvc}}",
     "measurement": "px_volume_halevel",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume total reads/writes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "alias": "Bytes Written Throughput",
     "expr": "px_volume_reads{cluster=~\"$Cluster\", exported_namespace=~\"$Namespace\", pvc=~\"$PVC\"}",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "No. of Reads - {{exported_namespace}}/{{pvc}}/{{volumename}}",
     "measurement": "px_volume_writethroughput",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Bytes Read Throughput",
     "expr": "px_volume_writes{cluster=~\"$Cluster\", exported_namespace=~\"$Namespace\", pvc=~\"$PVC\"}",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "No. of Writes - {{exported_namespace}}/{{pvc}}/{{volumename}}",
     "measurement": "px_volume_readthroughput",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume IOPs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "alias": "Bytes Written Throughput",
     "expr": "px_volume_iops{cluster=~\"$Cluster\", exported_namespace=~\"$Namespace\", pvc=~\"$PVC\"}",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "IOPs - {{exported_namespace}}/{{pvc}}/{{volumename}}",
     "measurement": "px_volume_writethroughput",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume Read/Written Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Bytes Written Throughput",
     "expr": "px_volume_read_bytes{cluster=~\"$Cluster\", exported_namespace=~\"$Namespace\", pvc=~\"$PVC\"}",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bytes Read - {{exported_namespace}}/{{pvc}}/{{volumename}}",
     "measurement": "px_volume_writethroughput",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Bytes Read Throughput",
     "expr": "px_volume_read_bytes{cluster=~\"$Cluster\", exported_namespace=~\"$Namespace\", pvc=~\"$PVC\"}",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bytes Written - {{exported_namespace}}/{{pvc}}/{{volumename}}",
     "measurement": "px_volume_readthroughput",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Read Latency",
     "expr": "px_volume_read_latency_seconds{cluster=~\"$Cluster\", exported_namespace=~\"$Namespace\", pvc=~\"$PVC\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "Read Latency - {{exported_namespace}}/{{pvc}}/{{volumename}}",
     "measurement": "px_volume_vol_read_latency_seconds",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Write Latency",
     "expr": "px_volume_write_latency_seconds{cluster=~\"$Cluster\", exported_namespace=~\"$Namespace\", pvc=~\"$PVC\"}\n",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "Write Latency - {{exported_namespace}}/{{pvc}}/{{volumename}}",
     "measurement": "px_volume_vol_write_latency_seconds",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume IO Depth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "px_volume_depth_io{cluster=~\"$Cluster\", exported_namespace=~\"$Namespace\", pvc=~\"$PVC\"}",
     "legendFormat": "I/O Depth - {{exported_namespace}}/{{pvc}}/{{volumename}}"
    }
   ]
  },
  {
   "title": "Volume Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Bytes Written Throughput",
     "expr": "px_volume_readthroughput{cluster=~\"$Cluster\", exported_namespace=~\"$Namespace\", pvc=~\"$PVC\"}",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bytes Read Throughput - {{exported_namespace}}/{{pvc}}/{{volumename}}",
     "measurement": "px_volume_writethroughput",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Bytes Read Throughput",
     "expr": "px_volume_writethroughput{cluster=~\"$Cluster\", exported_namespace=~\"$Namespace\", pvc=~\"$PVC\"}",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bytes Written Throughput - {{exported_namespace}}/{{pvc}}/{{volumename}}",
     "measurement": "px_volume_readthroughput",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  { "title": "Cloud Backup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Last Backup Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "px_backup_stats_backup_status{cluster=~\"$Cluster\"}",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Backup duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "px_backup_stats_backup_duration_seconds{cluster=~\"$Cluster\"} > 0",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Backup Duration (Avg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "px_backup_stats_backup_duration_seconds{cluster=~\"$Cluster\"} > 0",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Backup Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "px_backup_stats_backup_size{cluster=~\"$Cluster\"}",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Backup Size (Avg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "px_backup_stats_backup_size{cluster=~\"$Cluster\"}",
     "legendFormat": "{{volumename}}"
    }
   ]
  }
 ]
}