apiVersion: v1
kind: Namespace
metadata:
  name: mysql
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: px-mysql-pvc
   namespace: mysql
spec:
   storageClassName: px-csi-db
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      schedulerName: stork
      containers:
      - name: mysql
        image: mysql:9.2.0
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        env:
        - name: MYSQL_USER
          value: mysql
        - name: MYSQL_PASSWORD
          value: supermysql
        - name: MYSQL_DATABASE
          value: pxdemo
        - name: MYSQL_ROOT_PASSWORD
          value: supermysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: px-mysql-pvc
