apiVersion: stork.libopenstorage.org/v1alpha1
kind: Rule
metadata:
  name: px-mysql-presnap-rule
  namespace: mysql
rules:
  - podSelector:
      app: mysql
    actions:
    - type: command
      background: true
      # this command will flush tables with read lock
      value: mysql --system-command=ON --user=root --password=$MYSQL_ROOT_PASSWORD -Bse 'FLUSH TABLES WITH READ LOCK; SYSTEM ${WAIT_CMD};'