apiVersion: stork.libopenstorage.org/v1alpha1
kind: BackupLocation
metadata:
  name: minio
  namespace: backup-lab
  annotations:
    stork.libopenstorage.org/skipresource: "false"
location:
  type: s3
  sync: true
  path: "portworx"
  s3Config:
    region: default
    accessKeyID: minio
    secretAccessKey: minio123
    endpoint: "http://192.168.1<nn>.101:30221"
    disableSSL: true
