apiVersion: stork.libopenstorage.org/v1alpha1
kind: Migration
metadata:
  name: redis-migration
  namespace: kube-system
spec:
  clusterPair: CHANGEME
  includeResources: true
  startApplications: true
  namespaces:
  - CHANGEME
  purgeDeletedResources: false
