apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-cloudsnap-clone
  namespace: postgres
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: postgres-snapshot
spec:
  accessModes:
     - ReadWriteOnce
  storageClassName: stork-snapshot-sc
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-cloudsnap
  namespace: postgres
  labels:
    app: postgres-snap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-cloudsnap
  template:
    metadata:
      labels:
        app: postgres-cloudsnap
    spec:
      containers:
      - name: postgres
        image: postgres:17.5
        ports:
        - containerPort: 5432
        env:
        - name: PGUSER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data-from-snap
      volumes:
      - name: postgres-data-from-snap
        persistentVolumeClaim:
          claimName: postgres-cloudsnap-clone
