apiVersion: v1
kind: Service
metadata:
  name: px-backup-api-grpc
  namespace: central
spec:
  ports:
  - name: grpc
    port: 10002
    protocol: TCP
    targetPort: 10002
  selector:
    app: px-backup
  type: NodePort
