apiVersion: stork.libopenstorage.org/v1alpha1
kind: SchedulePolicy
metadata:
  name: 5-min
policy:
  interval:
    intervalMinutes: 5
---
apiVersion: stork.libopenstorage.org/v1alpha1
kind: MigrationSchedule
metadata:
  name: pxbbq-migration
  namespace: kube-system
spec:
  template:
    spec:
      clusterPair: remotecluster
      includeResources: true
      startApplications: false
      namespaces:
      - pxbbq
  schedulePolicyName: 5-min
