apiVersion: stork.libopenstorage.org/v1alpha1
kind: SchedulePolicy
metadata:
  name: 2-min
policy:
  interval:
    intervalMinutes: 2
---
apiVersion: stork.libopenstorage.org/v1alpha1
kind: MigrationSchedule
metadata:
  name: dr-schedule
  namespace: kube-system
spec:
  template:
    spec:
      clusterPair: remotecluster
      includeResources: true
      startApplications: false
      namespaces:
      - pxbbq
      - petclinic
  schedulePolicyName: 2-min
