apiVersion: stork.libopenstorage.org/v1alpha1
kind: SchedulePolicy
metadata:
  name: appschedule
  namespace: kube-system
policy:
  interval:
    intervalMinutes: 2
---
apiVersion: stork.libopenstorage.org/v1alpha1
kind: MigrationSchedule
metadata:
  name: appmigrationschedule
  namespace: kube-system
spec:
  template:
    spec:
      clusterPair: remotecluster-2
      includeResources: true
      startApplications: false
      includeVolumes: false
      namespaces:
      - pxbbq
      - petclinic
  schedulePolicyName: appschedule
