description: Deploys training clusters
scripts: ["training-cluster"]
px_version: 3.5.2
k8s_version: 1.33.5
run_predelete: true
cluster:
  - id: 1
    scripts: ["install-awscli", "etcd", "wetty", "snoop", "training-bastion"]
