description: Deploys training clusters
scripts: ["training-cluster"]
px_version: 3.5.1
k8s_version: 1.33.5
stop_after: 0
run_predelete: true
scripts: ["install-px", "training-backup-cluster"]
cluster:
  - id: 1
    scripts: ["install-awscli", "wetty", "snoop", "helm-backup", "training-backup-bastion"]
    nodes: 4
