description: Deploys training clusters
px_version: 3.5.1
k8s_version: 1.33.5
scripts: ["install-px", "training-backup-cluster"]
cluster:
  - id: 1
    scripts: ["install-awscli", "snoop", "helm-backup", "training-backup-bastion", "wetty" ]
    nodes: 4
env:
  pxb_version: "2.10.2"
